# 1 Dimesional Array

In [2]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


# 2dimesional (Matrix):

In [3]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print(arr2d.shape)

(3, 3)


In [13]:
print(arr2d.size)

9


# Indexing

In [14]:
print(arr[1])

2


In [19]:
print(arr2d[2])

[7 8 9]


In [20]:
print(arr[1])

2


# Slicing

In [22]:
print(arr[0:1])

[1]


In [27]:
print(arr2d[0:2])

[[1 2 3]
 [4 5 6]]


addition

In [6]:
x1=np.array([1,2,3])
x2=np.array([4,5,6])
print(x1+x2)

[5 7 9]


#  multiplication

In [5]:
print(x1*3)

NameError: name 'x1' is not defined

In [10]:
print(arr.dtype)

int64


In [11]:
print(arr2d.dtype)

int64


In [20]:
x=np.random.randint(0,10, size=[5,5])
print(x)

[[4 3 8 7 4]
 [1 8 7 4 1]
 [7 2 4 3 7]
 [5 4 0 0 4]
 [1 6 2 5 2]]


In [21]:
print(x[1])

[1 0 3 6 1]


In [26]:
print(x[1:3])

[[1 0 3 6 1]
 [2 9 6 4 7]]


In [18]:
print(x)

[1 2 3 4 5 6 7 8 9]


In [30]:
print(x[1:3,1:2])

[[0]
 [9]]


In [21]:
x=np.arange(1,20, size=[2,4])
print(x)

TypeError: arange() got an unexpected keyword argument 'size'

In [22]:
x=np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
x.size

12

In [26]:
x.dtype

dtype('float64')

In [27]:
x.ndim

2

In [28]:
x.shape

(3, 4)

In [30]:
x=np.ones((3,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [31]:
x.ndim

2

In [32]:
x.dtype

dtype('float64')